// src/components/MainContent.vue
<template>
  <div class="flex flex-col flex-auto">
    <navbar />
    <div class="flex flex-auto overflow-y-hidden bg-dc4">
      <div class="flex-grow">
        <channel-room />
      </div>
      <keep-alive>
        <component v-if="$store.getters.isUserTabOpen" :is="'UserList'" />
      </keep-alive>
    </div>
  </div>
</template>

<script>
import ChannelRoom from "./ChannelRoom";
import Navbar from "./Navbar";
import UserList from "./UserList";
export default {
  name: "MainContent",
  components: {
    Navbar,
    UserList,
    ChannelRoom,
  },
  data() {
    return {};
  },
  computed: {
    isUserListOpen() {
      return this.$store.getters.isUserTabOpen;
    },
  },
  methods: {},
};
</script>

// components/MainContent/index.tsx
"use client";

import React, { useEffect } from "react";
import Sidebar from "./Sidebar";
import Topbar from "./Topbar";
import ChannelRoom from "./ChannelRoom";
import { useServerStore } from "@/data/store";
import { Channel } from "@/data/types";

const MainContent = ({ channels }: { channels: Channel[] }) => {
  const setChannels = useServerStore((state) => state.setChannels);

  useEffect(() => {
    setChannels(channels);
  }, [channels]);

  return (
    <div className="flex h-screen overflow-hidden bg-bg3">
      <Sidebar />
      <div className="flex-auto" style={{ transition: "flex-grow 0.5s ease" }}>
        <div className="flex h-full">
          <div className="flex flex-col flex-auto">
            <div className="flex-none">
              <Topbar />
            </div>
            <div className="flex-auto overflow-hidden">
              <ChannelRoom />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MainContent;
